###A very horrible prototype

In [1]:
from collections import defaultdict
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
Data_set = \
['What is the RAM capacity of your Apple Computer?512MB',
'What is the color of apple fruit?Red',
'Is apple tastier than banana fruit?Nope I hate apples',
'Are apple computers better than windows PC?Yes,Apple is best because of good GUI',
'Why do I have to eat an apple a day?To Keep the doctor away',
'Does eating an apple help fight tooth decay?Yes,only if your brush your teeth',
'Who is the President of USA?Barrack Obama',
'What is the GDP of USA?13 trillion']

In [3]:
My_questions = 'Tell something about usa?'

In [4]:
questions = []
answers = []
for data in Data_set:
    questions.append(data.split("?")[0])
    answers.append(data.split("?")[1])
    
questions.append(My_questions)    
question_index = len(questions)-1

In [5]:
tfidf = TfidfVectorizer().fit_transform(questions)
pairwise_similarity = tfidf * tfidf.T
pairwise_similarity.todense()

matrix([[ 1.        ,  0.42213599,  0.12324278,  0.04516209,  0.04180383,
          0.04180383,  0.24957401,  0.38879852,  0.        ],
        [ 0.42213599,  1.        ,  0.34144775,  0.05744589,  0.0531742 ,
          0.0531742 ,  0.31745656,  0.49454926,  0.        ],
        [ 0.12324278,  0.34144775,  1.        ,  0.20026059,  0.05093777,
          0.05093777,  0.08659432,  0.09251823,  0.        ],
        [ 0.04516209,  0.05744589,  0.20026059,  1.        ,  0.0418149 ,
          0.0418149 ,  0.        ,  0.        ,  0.        ],
        [ 0.04180383,  0.0531742 ,  0.05093777,  0.0418149 ,  1.        ,
          0.14085451,  0.        ,  0.        ,  0.        ],
        [ 0.04180383,  0.0531742 ,  0.05093777,  0.0418149 ,  0.14085451,
          1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.24957401,  0.31745656,  0.08659432,  0.        ,  0.        ,
          0.        ,  1.        ,  0.49346246,  0.14869639],
        [ 0.38879852,  0.49454926,  0.09251823, 

### Windows vs Apple?

In [6]:
similarity_scores = pairwise_similarity.todense()[question_index][0].tolist()[0]
similarity_scores.remove(max(similarity_scores))
pred_question_index = similarity_scores.index(max(similarity_scores))
print answers[pred_question_index]

13 trillion


In [141]:
"""Softmax."""

scores = [1.0, 2.0, 3.0]

import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    x = np.array(x)
    x = x/10
    return np.exp(x) / np.sum(np.exp(x),axis=0)
print(softmax(scores))

# Plot softmax curves
import matplotlib.pyplot as plt
x = np.arange(-2.0, 6.0, 0.1)
scores = np.vstack([x, np.ones_like(x), 0.2 * np.ones_like(x)])


print(softmax(scores))
plt.plot(x, softmax(scores).T, linewidth=2)
plt.show()


[ 0.30060961  0.33222499  0.3671654 ]
[[ 0.27809175  0.28010376  0.28212465  0.28415436  0.28619285  0.28824007
   0.29029598  0.29236054  0.29443368  0.29651537  0.29860555  0.30070416
   0.30281115  0.30492647  0.30705006  0.30918186  0.31132181  0.31346985
   0.31562592  0.31778995  0.31996189  0.32214165  0.32432919  0.32652443
   0.32872729  0.33093772  0.33315563  0.33538095  0.33761361  0.33985354
   0.34210065  0.34435487  0.34661611  0.34888431  0.35115937  0.35344121
   0.35572975  0.3580249   0.36032658  0.3626347   0.36494917  0.3672699
   0.36959679  0.37192976  0.37426872  0.37661357  0.3789642   0.38132054
   0.38368248  0.38604991  0.38842275  0.39080089  0.39318423  0.39557266
   0.39796609  0.40036441  0.40276751  0.40517529  0.40758764  0.41000445
   0.41242562  0.41485103  0.41728058  0.41971414  0.42215162  0.4245929
   0.42703786  0.42948639  0.43193838  0.4343937   0.43685226  0.43931391
   0.44177856  0.44424608  0.44671635  0.44918926  0.45166468  0.45414249
  

In [118]:
print new_x
print new_x.reshape(3,)

[[ 0.09003057]
 [ 0.24472847]
 [ 0.66524096]]
[ 0.09003057  0.24472847  0.66524096]


In [103]:
x = np.array([[1,2,3,6],[2,4,5,6],[3,8,7,6]])
x = np.array([1,2,3])

In [108]:
x/float(x.sum(0))

array([ 0.16666667,  0.33333333,  0.5       ])